package com.each.adsc.blockingbutcher.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "meat_tb")
data class Meat(
    @DynamoDBHashKey(attributeName = "meat_id")
    @DynamoDBAutoGeneratedKey
    val meatId: String,

    @DynamoDBAttribute(attributeName = "name")
    val name: String,

    @DynamoDBAttribute(attributeName = "animal_of_origin")
    val animalOfOrigin: String,

    @DynamoDBAttribute(attributeName = "price")
    val price: Double,

    @DynamoDBAttribute(attributeName = "available_amount")
    val availableAmountInKilograms: Int
)
