package com.each.adsc.blockingbutcher.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import java.io.Serializable

@DynamoDBTable(tableName = "meat_tb")
data class Meat(
    @DynamoDBHashKey(attributeName = "meat_name")
    @DynamoDBAutoGeneratedKey
    var meatName: String = "",

    @DynamoDBAttribute(attributeName = "animal_of_origin")
    var animalOfOrigin: String = "",

    @DynamoDBAttribute(attributeName = "price")
    var price: Double = 0.0,

    @DynamoDBAttribute(attributeName = "available_amount")
    var availableAmountInKilograms: Double = 0.0
) : Serializable
