package com.each.adsc.blockingbutcher.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import java.io.Serializable
import java.time.LocalDateTime

@DynamoDBTable(tableName = "sale_tb")
data class Sale(
    @DynamoDBHashKey(attributeName = "sale_id")
    @DynamoDBAutoGeneratedKey
    var saleId: String? = null,

    @DynamoDBAttribute(attributeName = "meat_name")
    var meatName: String,

    @DynamoDBAttribute(attributeName = "amount")
    val amount: Double,

    @DynamoDBAttribute(attributeName = "total_price")
    var totalPrice: Double,

    @DynamoDBAttribute(attributeName = "type_of_cut")
    val typeOfCut: String,

    @DynamoDBAttribute(attributeName = "timestamp")
    var saleTimestamp: String = LocalDateTime.now().toString()
) : Serializable

