aws:
  dynamodb:
    endpoint: "http://localhost:8000"
    region: "us-east-1"
    accesskey: "default_access_key"
    secretkey: "default_secret_key"
    table:
      butcher: "meat_tb"
      purchase: "purchase_tb"
      sale: "sale_tb"
